default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: localhost
  user: postgres
  password: postgres

development:
  <<: *default
  database: travel_expenses_converter_development

test:
  <<: *default
  database: travel_expenses_converter_test

production:
  <<: *default
  database: travel_expenses_converter_production
  username: travel_expenses_converter
  password: <%= ENV['TCC_PRODUTO_DATABASE_PASSWORD'] %>
